const S=CMS.S={},A=t=>CMS.all(t),G=CMS.get;
S.slots=[];for(let h=9;h<17;h++)['00','30'].forEach(m=>S.slots.push(String(h).padStart(2,'0')+':'+m));
S.doctors=()=>A('users').filter(u=>u.role==='DOCTOR'&&u.is_active);
S.total=b=>b.items.reduce((s,i)=>s+i.amount,0);S.bal=b=>S.total(b)-b.paid;
S.bstat=b=>b.paid>=S.total(b)?'PAID':b.paid>0?'PARTIAL':'UNPAID';
const bill=(patient,desc,amount,ref)=>{let b=A('bills').find(b=>b.patient===patient&&S.bstat(b)!=='PAID');if(!b)b=CMS.add('bills',{patient,items:[],paid:0,date:CMS.today()},'B');b.items.push({desc,amount,ref})};
S.addPatient=v=>CMS.tx(()=>{if(A('patients').some(p=>p.phone===v.phone&&p.name.toLowerCase()===v.name.toLowerCase()))throw Error('This patient is already registered');return CMS.add('patients',{...v,registered:CMS.today(),is_active:true},'P')});
S.book=v=>CMS.tx(()=>{const p=G('patients',v.patient),d=G('users',v.doctor),now=new Date().toTimeString().slice(0,5);
if(!p||!p.is_active)throw Error('Patient is not active');if(!d||!d.is_active)throw Error('Doctor is not available');
if(v.date<CMS.today())throw Error('Cannot book in the past');if(v.date===CMS.today()&&v.slot<=now)throw Error('That slot has already passed');
const live=A('appointments').filter(a=>a.status==='SCHEDULED'&&a.date===v.date&&a.slot===v.slot);
if(live.some(a=>a.doctor===v.doctor))throw Error('Doctor is already booked at that time');
if(live.some(a=>a.patient===v.patient))throw Error('Patient already has an appointment at that time');
const a=CMS.add('appointments',{patient:v.patient,doctor:v.doctor,date:v.date,slot:v.slot,status:'SCHEDULED'},'A');bill(v.patient,'Consultation fee',300,a.id);return a});
S.cancel=id=>CMS.tx(()=>{const a=G('appointments',id);if(a.status!=='SCHEDULED')throw Error('Only scheduled appointments can be cancelled');
const b=A('bills').find(b=>b.items.some(i=>i.ref===id));if(b){if(b.paid>0)throw Error('Fee already paid — refunds are not supported');b.items=b.items.filter(i=>i.ref!==id)}a.status='CANCELLED'});
S.consult=(id,v)=>CMS.tx(()=>{const a=G('appointments',id);if(a.status!=='SCHEDULED')throw Error('Appointment is not open for consultation');Object.assign(a,{diagnosis:v.diagnosis,notes:v.notes||'',status:'COMPLETED'})});
const done=id=>{const a=G('appointments',id);if(!a||a.status!=='COMPLETED')throw Error('Complete the consultation first');return a};
S.prescribe=(id,v)=>CMS.tx(()=>{const a=done(id),m=G('medicines',v.medicine);if(!m||!m.is_active)throw Error('Medicine is not available');if(m.expiry<CMS.today())throw Error('Medicine is expired');
return CMS.add('prescriptions',{appt:id,patient:a.patient,doctor:a.doctor,medicine:m.id,qty:+v.qty,dosage:v.dosage,status:'PENDING'},'R')});
S.orderLab=(id,v)=>CMS.tx(()=>{const a=done(id);if(A('labOrders').some(o=>o.appt===id&&o.test===v.test&&o.status!=='COMPLETED'))throw Error('This test is already ordered');return CMS.add('labOrders',{appt:id,patient:a.patient,doctor:a.doctor,test:v.test,status:'ORDERED'},'L')});
S.dispense=id=>CMS.tx(()=>{const r=G('prescriptions',id),m=G('medicines',r.medicine);if(r.status!=='PENDING')throw Error('Prescription already handled');
if(!m.is_active)throw Error('Medicine is inactive');if(m.expiry<CMS.today())throw Error('Medicine is expired');if(m.stock<r.qty)throw Error(`Only ${m.stock} in stock, ${r.qty} needed`);
m.stock-=r.qty;bill(r.patient,`${m.name} × ${r.qty}`,m.price*r.qty,r.id);r.status='DISPENSED'});
S.labStart=id=>CMS.tx(()=>{const o=G('labOrders',id);if(o.status!=='ORDERED')throw Error('Test already started');o.status='IN_PROGRESS'});
S.labResult=(id,v)=>CMS.tx(()=>{const o=G('labOrders',id),t=G('labCatalog',o.test);if(o.status!=='IN_PROGRESS')throw Error('Start the test before entering a result');
o.result=v.result;o.flag=v.flag;o.status='COMPLETED';bill(o.patient,'Lab: '+t.name,t.price,o.id)});
S.pay=(id,amt)=>CMS.tx(()=>{const b=G('bills',id);if(+amt>S.bal(b))throw Error('Amount is more than the balance due');b.paid=Math.round((b.paid+ +amt)*100)/100});
const nm=(t,id)=>(G(t,id)||{}).name||'—';S.pn=id=>nm('patients',id);S.un=id=>nm('users',id);S.mn=id=>nm('medicines',id);S.tn=id=>nm('labCatalog',id);
